alias l='ls -lh --group-directories-first'
alias lt='ls -tlh --group-directories-first'
alias x='tmux new -s tarcisio'
alias a='tmux a'
alias k="~/Programs/main-venv/bin/buku"
alias grep='grep --color'
alias python='python3'
alias b='kitten ssh -p 49502 attilio@146.164.75.72'
alias t='ssh tarcisio@146.164.107.65'
alias bl='/usr/bin/bl'
alias token='cat ~/.token | xclip -sel clip'
alias st='/opt/st-0.9/st'
# alias nvim='/opt/nvim-linux64/bin/nvim'
alias reboot='systemctl reboot'
alias poweroff='systemctl poweroff'
alias cf='cpfrom'
alias ct='cpto'
alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
